spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://bid.c9y6oosooafq.ap-northeast-2.rds.amazonaws.com:3306/auction
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      format_sql: true
      ddl-auto: update
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


cloud:
  aws:
    s3:
      bucket: bid-auction-bucket
      path:
        postImage: auctionPosts/images
      credentials:
        access-key: AKIAVRUVQH5EAGXJRGU6
        secret-key: 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
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false

iamport:
  store-id: 5586626333704252
  api-key: imp52108063
  api-secret: ZJza35WRNjBrQbxjKkORdEFsZcanb6KgBFlWPo3FGJSVSzJmUq0Mpo4ygdjgSqCclN816KVewtwWwBCa

